### ISSUE TITLE
Adding a resource pack breaks export

### ISSUE THREAD

**Issue by michal212345** [BramStoutProductions/MiEx#21] opened 2024-04-24 17:21 UTC
The resource pack: https://www.curseforge.com/minecraft/texture-packs/minecraft-3d-default

In blender with UsdPreviewSurface on top of resourcepack
![image](https://github.com/BramStoutProductions/MiEx/assets/20019071/957349bc-caec-49d9-9476-b37aaf2ab895)

In Maya without the USDps on top
![image](https://github.com/BramStoutProductions/MiEx/assets/20019071/672521e4-e239-4b50-9e83-989f7828ad61)

**Comment by BramStout** [comment] 2024-04-24 17:39
I have just tried exporting out a world with that resource pack and I'm unable to reproduce this issue. Would you be able to zip up the USD files and share them here?

**Comment by michal212345** [comment] 2024-04-24 18:09
https://1drv.ms/u/s!Akq4O3d_-PVwo_Rel9w_0cnI26afIQ?e=9NCt3z

**Comment by michal212345** [comment] 2024-04-24 18:33
I think when I tried creating an atlas for the 3d blocks, it broke everything else? Because after deleting resources and not doing that, everything exported fine.

**Comment by BramStout** [comment] 2024-04-24 18:35
I've been able to reproduce it. It turns out that when you have multiple resource packs active each with atlases created, you'll get this issue. I already know how to fix this, so I'll get a new release out tomorrow that will fix this!

**Comment by BramStout** [comment] 2024-04-25 14:30
This has now been fixed in the latest release, which you can find here: https://github.com/BramStoutProductions/MiEx/releases/tag/v1.3.0

**Closed by BramStout** 2024-04-25 14:30 UTC
